package policies

import "github.com/pritunl/pritunl-cloud/cli/widget"

// The rule values below mirror the operating system, browser and
// location choices of the web policy rules in their web order.

var operatingSystemOptions = []widget.SelectOption{
	{Label: "Linux", Value: "linux"},
	{Label: "macOS 10.10", Value: "macos_1010"},
	{Label: "macOS 10.11", Value: "macos_1011"},
	{Label: "macOS 10.12", Value: "macos_1012"},
	{Label: "macOS 10.13", Value: "macos_1013"},
	{Label: "macOS 10.14", Value: "macos_1014"},
	{Label: "macOS 10.15", Value: "macos_1015"},
	{Label: "macOS 11", Value: "macos11"},
	{Label: "macOS 12", Value: "macos12"},
	{Label: "macOS 13", Value: "macos13"},
	{Label: "macOS 14", Value: "macos14"},
	{Label: "macOS 15", Value: "macos15"},
	{Label: "macOS 16", Value: "macos16"},
	{Label: "Windows XP", Value: "windows_xp"},
	{Label: "Windows 7", Value: "windows_7"},
	{Label: "Windows Vista", Value: "windows_vista"},
	{Label: "Windows 8", Value: "windows_8"},
	{Label: "Windows 10", Value: "windows_10"},
	{Label: "Windows 11", Value: "windows_11"},
	{Label: "Chrome OS", Value: "chrome_os"},
	{Label: "iOS 8", Value: "ios_8"},
	{Label: "iOS 9", Value: "ios_9"},
	{Label: "iOS 10", Value: "ios_10"},
	{Label: "iOS 11", Value: "ios_11"},
	{Label: "iOS 12", Value: "ios_12"},
	{Label: "iOS 13", Value: "ios_13"},
	{Label: "iOS 14", Value: "ios_14"},
	{Label: "iOS 15", Value: "ios_15"},
	{Label: "iOS 16", Value: "ios_16"},
	{Label: "iOS 17", Value: "ios_17"},
	{Label: "iOS 18", Value: "ios_18"},
	{Label: "iOS 19", Value: "ios_19"},
	{Label: "iOS 20", Value: "ios_20"},
	{Label: "Android KitKat 4.4", Value: "android_4"},
	{Label: "Android Lollipop 5", Value: "android_5"},
	{Label: "Android Marshmallow 6", Value: "android_6"},
	{Label: "Android Nougat 7", Value: "android_7"},
	{Label: "Android Oreo 8", Value: "android_8"},
	{Label: "Android Pie 9", Value: "android_9"},
	{Label: "Android 10", Value: "android_10"},
	{Label: "Android 11", Value: "android_11"},
	{Label: "Android 12", Value: "android_12"},
	{Label: "Android 13", Value: "android_13"},
	{Label: "Android 14", Value: "android_14"},
	{Label: "Android 15", Value: "android_15"},
	{Label: "Android 16", Value: "android_16"},
	{Label: "Blackerry 10", Value: "blackberry_10"},
	{Label: "Windows Phone", Value: "windows_phone"},
	{Label: "Firefox OS", Value: "firefox_os"},
	{Label: "Kindle", Value: "kindle"},
}

var browserOptions = []widget.SelectOption{
	{Label: "Chrome", Value: "chrome"},
	{Label: "Chrome Mobile", Value: "chrome_mobile"},
	{Label: "Safari", Value: "safari"},
	{Label: "Safari Mobile", Value: "safari_mobile"},
	{Label: "Firefox", Value: "firefox"},
	{Label: "Firefox Mobile", Value: "firefox_mobile"},
	{Label: "Microsoft Edge", Value: "edge"},
	{Label: "Internet Explorer", Value: "internet_explorer"},
	{Label: "Internet Explorer Mobile", Value: "internet_explorer_mobile"},
	{Label: "Opera", Value: "opera"},
	{Label: "Opera Mobile", Value: "opera_mobile"},
}

var locationOptions = []widget.SelectOption{
	{Label: "United States", Value: "US"},
	{Label: "Alabama, US", Value: "US_AL"},
	{Label: "Alaska, US", Value: "US_AK"},
	{Label: "Arizona, US", Value: "US_AZ"},
	{Label: "Arkansas, US", Value: "US_AR"},
	{Label: "California, US", Value: "US_CA"},
	{Label: "Colorado, US", Value: "US_CO"},
	{Label: "Connecticut, US", Value: "US_CT"},
	{Label: "Delaware, US", Value: "US_DE"},
	{Label: "Florida, US", Value: "US_FL"},
	{Label: "Georgia, US", Value: "US_GA"},
	{Label: "Hawaii, US", Value: "US_HI"},
	{Label: "Idaho, US", Value: "US_ID"},
	{Label: "Illinois, US", Value: "US_IL"},
	{Label: "Indiana, US", Value: "US_IN"},
	{Label: "Iowa, US", Value: "US_IA"},
	{Label: "Kansas, US", Value: "US_KS"},
	{Label: "Kentucky, US", Value: "US_KY"},
	{Label: "Louisiana, US", Value: "US_LA"},
	{Label: "Maine, US", Value: "US_ME"},
	{Label: "Maryland, US", Value: "US_MD"},
	{Label: "Massachusetts, US", Value: "US_MA"},
	{Label: "Michigan, US", Value: "US_MI"},
	{Label: "Minnesota, US", Value: "US_MN"},
	{Label: "Mississippi, US", Value: "US_MS"},
	{Label: "Missouri, US", Value: "US_MO"},
	{Label: "Montana, US", Value: "US_MT"},
	{Label: "Nebraska, US", Value: "US_NE"},
	{Label: "Nevada, US", Value: "US_NV"},
	{Label: "New Hampshire, US", Value: "US_NH"},
	{Label: "New Jersey, US", Value: "US_NJ"},
	{Label: "New Mexico, US", Value: "US_NM"},
	{Label: "New York, US", Value: "US_NY"},
	{Label: "North Carolina, US", Value: "US_NC"},
	{Label: "North Dakota, US", Value: "US_ND"},
	{Label: "Ohio, US", Value: "US_OH"},
	{Label: "Oklahoma, US", Value: "US_OK"},
	{Label: "Oregon, US", Value: "US_OR"},
	{Label: "Pennsylvania, US", Value: "US_PA"},
	{Label: "Rhode Island, US", Value: "US_RI"},
	{Label: "South Carolina, US", Value: "US_SC"},
	{Label: "South Dakota, US", Value: "US_SD"},
	{Label: "Tennessee, US", Value: "US_TN"},
	{Label: "Texas, US", Value: "US_TX"},
	{Label: "Utah, US", Value: "US_UT"},
	{Label: "Vermont, US", Value: "US_VT"},
	{Label: "Virginia, US", Value: "US_VA"},
	{Label: "Washington, US", Value: "US_WA"},
	{Label: "Washington DC, US", Value: "US_DC"},
	{Label: "West Virginia, US", Value: "US_WV"},
	{Label: "Wisconsin, US", Value: "US_WI"},
	{Label: "Wyoming, US", Value: "US_WY"},
	{Label: "Afghanistan", Value: "AF"},
	{Label: "Åland Islands", Value: "AX"},
	{Label: "Albania", Value: "AL"},
	{Label: "Algeria", Value: "DZ"},
	{Label: "American Samoa", Value: "AS"},
	{Label: "Andorra", Value: "AD"},
	{Label: "Angola", Value: "AO"},
	{Label: "Anguilla", Value: "AI"},
	{Label: "Antarctica", Value: "AQ"},
	{Label: "Antigua and Barbuda", Value: "AG"},
	{Label: "Argentina", Value: "AR"},
	{Label: "Armenia", Value: "AM"},
	{Label: "Aruba", Value: "AW"},
	{Label: "Australia", Value: "AU"},
	{Label: "Austria", Value: "AT"},
	{Label: "Azerbaijan", Value: "AZ"},
	{Label: "Bahamas", Value: "BS"},
	{Label: "Bahrain", Value: "BH"},
	{Label: "Bangladesh", Value: "BD"},
	{Label: "Barbados", Value: "BB"},
	{Label: "Belarus", Value: "BY"},
	{Label: "Belgium", Value: "BE"},
	{Label: "Belize", Value: "BZ"},
	{Label: "Benin", Value: "BJ"},
	{Label: "Bermuda", Value: "BM"},
	{Label: "Bhutan", Value: "BT"},
	{Label: "Bolivia", Value: "BO"},
	{Label: "Bonaire", Value: "BQ"},
	{Label: "Bosnia and Herzegovina", Value: "BA"},
	{Label: "Botswana", Value: "BW"},
	{Label: "Bouvet Island", Value: "BV"},
	{Label: "Brazil", Value: "BR"},
	{Label: "British Indian Ocean Territory", Value: "IO"},
	{Label: "Brunei Darussalam", Value: "BN"},
	{Label: "Bulgaria", Value: "BG"},
	{Label: "Burkina Faso", Value: "BF"},
	{Label: "Burundi", Value: "BI"},
	{Label: "Cabo Verde", Value: "CV"},
	{Label: "Cambodia", Value: "KH"},
	{Label: "Cameroon", Value: "CM"},
	{Label: "Canada", Value: "CA"},
	{Label: "Cayman Islands", Value: "KY"},
	{Label: "Central African Republic", Value: "CF"},
	{Label: "Chad", Value: "TD"},
	{Label: "Chile", Value: "CL"},
	{Label: "China", Value: "CN"},
	{Label: "Christmas Island", Value: "CX"},
	{Label: "Cocos Islands", Value: "CC"},
	{Label: "Colombia", Value: "CO"},
	{Label: "Comoros", Value: "KM"},
	{Label: "Congo", Value: "CG"},
	{Label: "Congo Democratic Republic", Value: "CD"},
	{Label: "Cook Islands", Value: "CK"},
	{Label: "Costa Rica", Value: "CR"},
	{Label: "Côte dIvoire", Value: "CI"},
	{Label: "Croatia", Value: "HR"},
	{Label: "Cuba", Value: "CU"},
	{Label: "Curaçao", Value: "CW"},
	{Label: "Cyprus", Value: "CY"},
	{Label: "Czechia", Value: "CZ"},
	{Label: "Denmark", Value: "DK"},
	{Label: "Djibouti", Value: "DJ"},
	{Label: "Dominica", Value: "DM"},
	{Label: "Dominican Republic", Value: "DO"},
	{Label: "Ecuador", Value: "EC"},
	{Label: "Egypt", Value: "EG"},
	{Label: "El Salvador", Value: "SV"},
	{Label: "Equatorial Guinea", Value: "GQ"},
	{Label: "Eritrea", Value: "ER"},
	{Label: "Estonia", Value: "EE"},
	{Label: "Ethiopia", Value: "ET"},
	{Label: "Falkland Islands", Value: "FK"},
	{Label: "Faroe Islands", Value: "FO"},
	{Label: "Fiji", Value: "FJ"},
	{Label: "Finland", Value: "FI"},
	{Label: "France", Value: "FR"},
	{Label: "French Guiana", Value: "GF"},
	{Label: "French Polynesia", Value: "PF"},
	{Label: "French Southern Territories", Value: "TF"},
	{Label: "Gabon", Value: "GA"},
	{Label: "Gambia", Value: "GM"},
	{Label: "Georgia", Value: "GE"},
	{Label: "Germany", Value: "DE"},
	{Label: "Ghana", Value: "GH"},
	{Label: "Gibraltar", Value: "GI"},
	{Label: "Greece", Value: "GR"},
	{Label: "Greenland", Value: "GL"},
	{Label: "Grenada", Value: "GD"},
	{Label: "Guadeloupe", Value: "GP"},
	{Label: "Guam", Value: "GU"},
	{Label: "Guatemala", Value: "GT"},
	{Label: "Guernsey", Value: "GG"},
	{Label: "Guinea", Value: "GN"},
	{Label: "Guinea-Bissau", Value: "GW"},
	{Label: "Guyana", Value: "GY"},
	{Label: "Haiti", Value: "HT"},
	{Label: "Heard Island and McDonald Islands", Value: "HM"},
	{Label: "Holy See", Value: "VA"},
	{Label: "Honduras", Value: "HN"},
	{Label: "Hong Kong", Value: "HK"},
	{Label: "Hungary", Value: "HU"},
	{Label: "Iceland", Value: "IS"},
	{Label: "India", Value: "IN"},
	{Label: "Indonesia", Value: "ID"},
	{Label: "Iran", Value: "IR"},
	{Label: "Iraq", Value: "IQ"},
	{Label: "Ireland", Value: "IE"},
	{Label: "Isle of Man", Value: "IM"},
	{Label: "Israel", Value: "IL"},
	{Label: "Italy", Value: "IT"},
	{Label: "Jamaica", Value: "JM"},
	{Label: "Japan", Value: "JP"},
	{Label: "Jersey", Value: "JE"},
	{Label: "Jordan", Value: "JO"},
	{Label: "Kazakhstan", Value: "KZ"},
	{Label: "Kenya", Value: "KE"},
	{Label: "Kiribati", Value: "KI"},
	{Label: "North Korea", Value: "KP"},
	{Label: "South Korea", Value: "KR"},
	{Label: "Kuwait", Value: "KW"},
	{Label: "Kyrgyzstan", Value: "KG"},
	{Label: "Lao Peoples", Value: "LA"},
	{Label: "Latvia", Value: "LV"},
	{Label: "Lebanon", Value: "LB"},
	{Label: "Lesotho", Value: "LS"},
	{Label: "Liberia", Value: "LR"},
	{Label: "Libya", Value: "LY"},
	{Label: "Liechtenstein", Value: "LI"},
	{Label: "Lithuania", Value: "LT"},
	{Label: "Luxembourg", Value: "LU"},
	{Label: "Macao", Value: "MO"},
	{Label: "Macedonia", Value: "MK"},
	{Label: "Madagascar", Value: "MG"},
	{Label: "Malawi", Value: "MW"},
	{Label: "Malaysia", Value: "MY"},
	{Label: "Maldives", Value: "MV"},
	{Label: "Mali", Value: "ML"},
	{Label: "Malta", Value: "MT"},
	{Label: "Marshall Islands", Value: "MH"},
	{Label: "Martinique", Value: "MQ"},
	{Label: "Mauritania", Value: "MR"},
	{Label: "Mauritius", Value: "MU"},
	{Label: "Mayotte", Value: "YT"},
	{Label: "Mexico", Value: "MX"},
	{Label: "Micronesia", Value: "FM"},
	{Label: "Moldova", Value: "MD"},
	{Label: "Monaco", Value: "MC"},
	{Label: "Mongolia", Value: "MN"},
	{Label: "Montenegro", Value: "ME"},
	{Label: "Montserrat", Value: "MS"},
	{Label: "Morocco", Value: "MA"},
	{Label: "Mozambique", Value: "MZ"},
	{Label: "Myanmar", Value: "MM"},
	{Label: "Namibia", Value: "NA"},
	{Label: "Nauru", Value: "NR"},
	{Label: "Nepal", Value: "NP"},
	{Label: "Netherlands", Value: "NL"},
	{Label: "New Caledonia", Value: "NC"},
	{Label: "New Zealand", Value: "NZ"},
	{Label: "Nicaragua", Value: "NI"},
	{Label: "Niger", Value: "NE"},
	{Label: "Nigeria", Value: "NG"},
	{Label: "Niue", Value: "NU"},
	{Label: "Norfolk Island", Value: "NF"},
	{Label: "Northern Mariana Islands", Value: "MP"},
	{Label: "Norway", Value: "NO"},
	{Label: "Oman", Value: "OM"},
	{Label: "Pakistan", Value: "PK"},
	{Label: "Palau", Value: "PW"},
	{Label: "Palestine, State of", Value: "PS"},
	{Label: "Panama", Value: "PA"},
	{Label: "Papua New Guinea", Value: "PG"},
	{Label: "Paraguay", Value: "PY"},
	{Label: "Peru", Value: "PE"},
	{Label: "Philippines", Value: "PH"},
	{Label: "Pitcairn", Value: "PN"},
	{Label: "Poland", Value: "PL"},
	{Label: "Portugal", Value: "PT"},
	{Label: "Puerto Rico", Value: "PR"},
	{Label: "Qatar", Value: "QA"},
	{Label: "Réunion", Value: "RE"},
	{Label: "Romania", Value: "RO"},
	{Label: "Russian Federation", Value: "RU"},
	{Label: "Rwanda", Value: "RW"},
	{Label: "Saint Barthélemy", Value: "BL"},
	{Label: "Saint Helena", Value: "SH"},
	{Label: "Saint Kitts and Nevis", Value: "KN"},
	{Label: "Saint Lucia", Value: "LC"},
	{Label: "Saint Martin", Value: "MF"},
	{Label: "Saint Pierre and Miquelon", Value: "PM"},
	{Label: "Saint Vincent and the Grenadines", Value: "VC"},
	{Label: "Samoa", Value: "WS"},
	{Label: "San Marino", Value: "SM"},
	{Label: "Sao Tome and Principe", Value: "ST"},
	{Label: "Saudi Arabia", Value: "SA"},
	{Label: "Senegal", Value: "SN"},
	{Label: "Serbia", Value: "RS"},
	{Label: "Seychelles", Value: "SC"},
	{Label: "Sierra Leone", Value: "SL"},
	{Label: "Singapore", Value: "SG"},
	{Label: "Sint Maarten", Value: "SX"},
	{Label: "Slovakia", Value: "SK"},
	{Label: "Slovenia", Value: "SI"},
	{Label: "Solomon Islands", Value: "SB"},
	{Label: "Somalia", Value: "SO"},
	{Label: "South Africa", Value: "ZA"},
	{Label: "South Georgia and the South Sandwich Islands", Value: "GS"},
	{Label: "South Sudan", Value: "SS"},
	{Label: "Spain", Value: "ES"},
	{Label: "Sri Lanka", Value: "LK"},
	{Label: "Sudan", Value: "SD"},
	{Label: "Suriname", Value: "SR"},
	{Label: "Svalbard and Jan Mayen", Value: "SJ"},
	{Label: "Swaziland", Value: "SZ"},
	{Label: "Sweden", Value: "SE"},
	{Label: "Switzerland", Value: "CH"},
	{Label: "Syrian Arab Republic", Value: "SY"},
	{Label: "Taiwan", Value: "TW"},
	{Label: "Tajikistan", Value: "TJ"},
	{Label: "Tanzania", Value: "TZ"},
	{Label: "Thailand", Value: "TH"},
	{Label: "Timor-Leste", Value: "TL"},
	{Label: "Togo", Value: "TG"},
	{Label: "Tokelau", Value: "TK"},
	{Label: "Tonga", Value: "TO"},
	{Label: "Trinidad and Tobago", Value: "TT"},
	{Label: "Tunisia", Value: "TN"},
	{Label: "Turkey", Value: "TR"},
	{Label: "Turkmenistan", Value: "TM"},
	{Label: "Turks and Caicos Islands", Value: "TC"},
	{Label: "Tuvalu", Value: "TV"},
	{Label: "Uganda", Value: "UG"},
	{Label: "Ukraine", Value: "UA"},
	{Label: "United Arab Emirates", Value: "AE"},
	{Label: "United Kingdom", Value: "GB"},
	{Label: "United States Minor Outlying Islands", Value: "UM"},
	{Label: "Uruguay", Value: "UY"},
	{Label: "Uzbekistan", Value: "UZ"},
	{Label: "Vanuatu", Value: "VU"},
	{Label: "Venezuela", Value: "VE"},
	{Label: "Viet Nam", Value: "VN"},
	{Label: "British Virgin Islands", Value: "VG"},
	{Label: "US Virgin Islands", Value: "VI"},
	{Label: "Wallis and Futuna", Value: "WF"},
	{Label: "Western Sahara", Value: "EH"},
	{Label: "Yemen", Value: "YE"},
	{Label: "Zambia", Value: "ZM"},
	{Label: "Zimbabwe", Value: "ZW"},
}
