package demo

import (
	"time"

	"github.com/pritunl/mongo-go-driver/bson/primitive"
	"github.com/pritunl/pritunl-cloud/cloud"
	"github.com/pritunl/pritunl-cloud/constants"
	"github.com/pritunl/pritunl-cloud/drive"
	"github.com/pritunl/pritunl-cloud/ip"
	"github.com/pritunl/pritunl-cloud/node"
	"github.com/pritunl/pritunl-cloud/pci"
	"github.com/pritunl/pritunl-cloud/usb"
	"github.com/pritunl/pritunl-cloud/utils"
)

var Nodes = []*node.Node{
	{
		Id:                   utils.ObjectIdHex("689733b2a7a35eae0dbaea0a"),
		Datacenter:           utils.ObjectIdHex("689733b7a7a35eae0dbaea1b"),
		Zone:                 utils.ObjectIdHex("689733b7a7a35eae0dbaea1e"),
		Name:                 "pritunl-east0",
		Comment:              "",
		Types:                []string{"admin", "hypervisor"},
		Timestamp:            time.Now(),
		Port:                 443,
		NoRedirectServer:     false,
		Protocol:             "https",
		Hypervisor:           "kvm",
		Vga:                  "virtio",
		VgaRender:            "",
		AvailableRenders:     []string{},
		Gui:                  false,
		GuiUser:              "",
		GuiMode:              "",
		Certificates:         []primitive.ObjectID{},
		AdminDomain:          "",
		UserDomain:           "",
		WebauthnDomain:       "",
		RequestsMin:          23,
		ForwardedForHeader:   "",
		ForwardedProtoHeader: "",
		ExternalInterfaces:   []string{},
		ExternalInterfaces6:  []string{},
		InternalInterfaces:   []string{"bond0.2"},
		AvailableInterfaces: []ip.Interface{
			{Name: "bond0", Address: ""},
			{Name: "bond0.2", Address: "10.8.0.10"},
			{Name: "bond0.4", Address: "10.253.67.90"},
			{Name: "bonding_masters", Address: ""},
			{Name: "enp1s0f0", Address: ""},
			{Name: "enp1s0f1", Address: ""},
			{Name: "veth0", Address: ""},
		},
		AvailableBridges: []ip.Interface{
			{Name: "pritunlhost0", Address: "198.18.84.1"},
			{Name: "pritunlport0", Address: "198.19.96.1"},
		},
		AvailableVpcs:    []*cloud.Vpc{},
		CloudSubnets:     []string{},
		DefaultInterface: "bond0.4",
		NetworkMode:      "static",
		NetworkMode6:     "static",
		Blocks: []*node.BlockAttachment{
			{
				Interface: "bond0.4",
				Block:     utils.ObjectIdHex("689733b7a7a35eae0dbaea2f"),
			},
		},
		Blocks6: []*node.BlockAttachment{
			{
				Interface: "bond0.4",
				Block:     utils.ObjectIdHex("68973a47b5844593cf99cc7a"),
			},
		},
		Pools:  []primitive.ObjectID{},
		Shares: []*node.Share{},
		AvailableDrives: []*drive.Device{
			{Id: "nvme-INTEL_27Z1P0FGN"},
			{Id: "nvme-INTEL_27Z1P0FGN-part1"},
			{Id: "nvme-INTEL_27Z1P0FGN-part2"},
			{Id: "nvme-INTEL_27Z1P0FGN-part3"},
			{Id: "nvme-INTEL_42K1P0FGN"},
			{Id: "nvme-INTEL_42K1P0FGN-part1"},
			{Id: "nvme-INTEL_42K1P0FGN-part2"},
			{Id: "nvme-INTEL_42K1P0FGN-part3"},
		},
		InstanceDrives:          []*drive.Device{},
		NoHostNetwork:           false,
		NoNodePortNetwork:       false,
		HostNat:                 true,
		DefaultNoPublicAddress:  true,
		DefaultNoPublicAddress6: false,
		JumboFrames:             true,
		JumboFramesInternal:     true,
		Iscsi:                   false,
		LocalIsos:               nil,
		UsbPassthrough:          false,
		UsbDevices:              []*usb.Device{},
		PciPassthrough:          false,
		PciDevices:              []*pci.Device{},
		Hugepages:               false,
		HugepagesSize:           0,
		Firewall:                false,
		Roles:                   []string{"shape-m2"},
		Memory:                  41.02,
		HugePagesUsed:           0,
		Load1:                   43.17,
		Load5:                   43.33,
		Load15:                  43.83,
		CpuUnits:                128,
		MemoryUnits:             512,
		CpuUnitsRes:             68,
		MemoryUnitsRes:          198,
		PublicIps:               []string{"10.253.67.90"},
		PublicIps6: []string{
			"2001:db8:85a3:4d2f:1319:8a2e:370:7348",
		},
		PrivateIps: map[string]string{
			"bond0.2": "10.8.0.10",
		},
		SoftwareVersion: constants.Version,
		Hostname:        "pritunl-east0",
		VirtPath:        "/var/lib/pritunl-cloud",
		CachePath:       "/var/cache/pritunl-cloud",
		TempPath:        "",
		OracleUser:      "",
		OracleTenancy:   "",
		OraclePublicKey: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxWtYOIzsHsLlBI1jeepJ
q8dyR1JH3QLdAJ2IFGZDtHCCi46Lvmx7hC8bAutj5s37qOfBrom6UOJf0f9zEP8K
y8qTb2S4XOAWBHuGpaBqFEhtpW+vIxiy26vdZN85P3xzYle0uodr86+y2bVHMHKB
0oEHnqu+CmH/r4GedBVFVBASo9C5iILsyISf4oep390V/u23RAXXNfcKvUYR4c2u
fZBwlSVEDrK+X21ocJc+8VGbbLhXBvMEdqXzs1bbFzFHow8TjduxDNTbntIRpo6W
0O7xMahUHxDWDro5fAkzvpk6wUBM6yWXXgwkDLLHW50dUnqgFJgOTIHXEtPSt4eU
2wIDAQAB
-----END PUBLIC KEY-----`,
		Operation: "",
	},
	{
		Id:                   utils.ObjectIdHex("689733b2a7a35eae0dbaea0b"),
		Datacenter:           utils.ObjectIdHex("689733b7a7a35eae0dbaea1b"),
		Zone:                 utils.ObjectIdHex("689733b7a7a35eae0dbaea1e"),
		Name:                 "pritunl-east1",
		Comment:              "",
		Types:                []string{"admin", "hypervisor"},
		Timestamp:            time.Now(),
		Port:                 443,
		NoRedirectServer:     false,
		Protocol:             "https",
		Hypervisor:           "kvm",
		Vga:                  "virtio",
		VgaRender:            "",
		AvailableRenders:     []string{},
		Gui:                  false,
		GuiUser:              "",
		GuiMode:              "",
		Certificates:         []primitive.ObjectID{},
		AdminDomain:          "",
		UserDomain:           "",
		WebauthnDomain:       "",
		RequestsMin:          44,
		ForwardedForHeader:   "",
		ForwardedProtoHeader: "",
		ExternalInterfaces:   []string{},
		ExternalInterfaces6:  []string{},
		InternalInterfaces:   []string{"bond0.2"},
		AvailableInterfaces: []ip.Interface{
			{Name: "bond0", Address: ""},
			{Name: "bond0.2", Address: "10.8.0.11"},
			{Name: "bond0.4", Address: "10.253.67.91"},
			{Name: "bonding_masters", Address: ""},
			{Name: "enp1s0f0", Address: ""},
			{Name: "enp1s0f1", Address: ""},
			{Name: "veth0", Address: ""},
		},
		AvailableBridges: []ip.Interface{
			{Name: "pritunlhost0", Address: "198.18.84.1"},
			{Name: "pritunlport0", Address: "198.19.96.1"},
		},
		AvailableVpcs:    []*cloud.Vpc{},
		CloudSubnets:     []string{},
		DefaultInterface: "bond0.4",
		NetworkMode:      "static",
		NetworkMode6:     "static",
		Blocks: []*node.BlockAttachment{
			{
				Interface: "bond0.4",
				Block:     utils.ObjectIdHex("689733b7a7a35eae0dbaea2f"),
			},
		},
		Blocks6: []*node.BlockAttachment{
			{
				Interface: "bond0.4",
				Block:     utils.ObjectIdHex("68973a47b5844593cf99cc7a"),
			},
		},
		Pools:  []primitive.ObjectID{},
		Shares: []*node.Share{},
		AvailableDrives: []*drive.Device{
			{Id: "nvme-INTEL_27Z1P0FGN"},
			{Id: "nvme-INTEL_27Z1P0FGN-part1"},
			{Id: "nvme-INTEL_27Z1P0FGN-part2"},
			{Id: "nvme-INTEL_27Z1P0FGN-part3"},
			{Id: "nvme-INTEL_42K1P0FGN"},
			{Id: "nvme-INTEL_42K1P0FGN-part1"},
			{Id: "nvme-INTEL_42K1P0FGN-part2"},
			{Id: "nvme-INTEL_42K1P0FGN-part3"},
		},
		InstanceDrives:          []*drive.Device{},
		NoHostNetwork:           false,
		NoNodePortNetwork:       false,
		HostNat:                 true,
		DefaultNoPublicAddress:  true,
		DefaultNoPublicAddress6: false,
		JumboFrames:             true,
		JumboFramesInternal:     true,
		Iscsi:                   false,
		LocalIsos:               nil,
		UsbPassthrough:          false,
		UsbDevices:              []*usb.Device{},
		PciPassthrough:          false,
		PciDevices:              []*pci.Device{},
		Hugepages:               false,
		HugepagesSize:           0,
		Firewall:                false,
		Roles:                   []string{"shape-m2"},
		Memory:                  62.02,
		HugePagesUsed:           0,
		Load1:                   67.12,
		Load5:                   57.43,
		Load15:                  55.23,
		CpuUnits:                128,
		MemoryUnits:             512,
		CpuUnitsRes:             78,
		MemoryUnitsRes:          324,
		PublicIps:               []string{"10.253.67.91"},
		PublicIps6: []string{
			"2001:db8:85a3:4d2f:7c3a:9f42:8e5b:a234",
		},
		PrivateIps: map[string]string{
			"bond0.2": "10.8.0.11",
		},
		SoftwareVersion: constants.Version,
		Hostname:        "pritunl-east0",
		VirtPath:        "/var/lib/pritunl-cloud",
		CachePath:       "/var/cache/pritunl-cloud",
		TempPath:        "",
		OracleUser:      "",
		OracleTenancy:   "",
		OraclePublicKey: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz4K8Lm3QvR7WxN5YdE2P
jX9TpQ6HgM1wV0nS4KaF3ZcB8LrY5UvO2JmN7XsPqI1AgK8EoH3RdWzM9LfY2VtN
kP4QxGsJ7YnR8LwVmT3AqZ5HvK2NdP1XoS8JgR4LmW7YxQ3VnH5TsK9PpL2MdX8Rg
vJ3KqN5WxT1LsM4HgY7RdP8NqV2JmK5XwL3TsR8YgN4HxP1LdK9VwQ2MsT3XpR7Y
nL8KgJ5WdH3TmR9XsL2PqN7VxK4MgT3HdJ8YwP2LsK5RxT1NqM4JgY7PxR8WsL3T
mK9XwN2HgJ5YdL3RsP8VqT2MxK4NhR3JdY8WwL2TsM5QxN1PqK4YgJ7RxP8VsT3M
PwIDAQAB
-----END PUBLIC KEY-----`,
		Operation: "",
	},
	{
		Id:                   utils.ObjectIdHex("689733b2a7a35eae0dbaea0c"),
		Datacenter:           utils.ObjectIdHex("689733b7a7a35eae0dbaea1b"),
		Zone:                 utils.ObjectIdHex("689733b7a7a35eae0dbaea1e"),
		Name:                 "pritunl-east2",
		Comment:              "",
		Types:                []string{"admin", "hypervisor"},
		Timestamp:            time.Now(),
		Port:                 443,
		NoRedirectServer:     false,
		Protocol:             "https",
		Hypervisor:           "kvm",
		Vga:                  "virtio",
		VgaRender:            "",
		AvailableRenders:     []string{},
		Gui:                  false,
		GuiUser:              "",
		GuiMode:              "",
		Certificates:         []primitive.ObjectID{},
		AdminDomain:          "",
		UserDomain:           "",
		WebauthnDomain:       "",
		RequestsMin:          26,
		ForwardedForHeader:   "",
		ForwardedProtoHeader: "",
		ExternalInterfaces:   []string{},
		ExternalInterfaces6:  []string{},
		InternalInterfaces:   []string{"bond0.2"},
		AvailableInterfaces: []ip.Interface{
			{Name: "bond0", Address: ""},
			{Name: "bond0.2", Address: "10.8.0.12"},
			{Name: "bond0.4", Address: "10.253.67.92"},
			{Name: "bonding_masters", Address: ""},
			{Name: "enp1s0f0", Address: ""},
			{Name: "enp1s0f1", Address: ""},
			{Name: "veth0", Address: ""},
		},
		AvailableBridges: []ip.Interface{
			{Name: "pritunlhost0", Address: "198.18.84.1"},
			{Name: "pritunlport0", Address: "198.19.96.1"},
		},
		AvailableVpcs:    []*cloud.Vpc{},
		CloudSubnets:     []string{},
		DefaultInterface: "bond0.4",
		NetworkMode:      "static",
		NetworkMode6:     "static",
		Blocks: []*node.BlockAttachment{
			{
				Interface: "bond0.4",
				Block:     utils.ObjectIdHex("689733b7a7a35eae0dbaea2f"),
			},
		},
		Blocks6: []*node.BlockAttachment{
			{
				Interface: "bond0.4",
				Block:     utils.ObjectIdHex("68973a47b5844593cf99cc7a"),
			},
		},
		Pools:  []primitive.ObjectID{},
		Shares: []*node.Share{},
		AvailableDrives: []*drive.Device{
			{Id: "nvme-INTEL_27Z1P0FGN"},
			{Id: "nvme-INTEL_27Z1P0FGN-part1"},
			{Id: "nvme-INTEL_27Z1P0FGN-part2"},
			{Id: "nvme-INTEL_27Z1P0FGN-part3"},
			{Id: "nvme-INTEL_42K1P0FGN"},
			{Id: "nvme-INTEL_42K1P0FGN-part1"},
			{Id: "nvme-INTEL_42K1P0FGN-part2"},
			{Id: "nvme-INTEL_42K1P0FGN-part3"},
		},
		InstanceDrives:          []*drive.Device{},
		NoHostNetwork:           false,
		NoNodePortNetwork:       false,
		HostNat:                 true,
		DefaultNoPublicAddress:  true,
		DefaultNoPublicAddress6: false,
		JumboFrames:             true,
		JumboFramesInternal:     true,
		Iscsi:                   false,
		LocalIsos:               nil,
		UsbPassthrough:          false,
		UsbDevices:              []*usb.Device{},
		PciPassthrough:          false,
		PciDevices:              []*pci.Device{},
		Hugepages:               false,
		HugepagesSize:           0,
		Firewall:                false,
		Roles:                   []string{"shape-m2"},
		Memory:                  41.02,
		HugePagesUsed:           0,
		Load1:                   76.53,
		Load5:                   67.34,
		Load15:                  67.87,
		CpuUnits:                128,
		MemoryUnits:             512,
		CpuUnitsRes:             56,
		MemoryUnitsRes:          286,
		PublicIps:               []string{"10.253.67.92"},
		PublicIps6: []string{
			"2001:db8:85a3:4d2f:2e91:5cd8:f1a6:7b89",
		},
		PrivateIps: map[string]string{
			"bond0.2": "10.8.0.12",
		},
		SoftwareVersion: constants.Version,
		Hostname:        "pritunl-east0",
		VirtPath:        "/var/lib/pritunl-cloud",
		CachePath:       "/var/cache/pritunl-cloud",
		TempPath:        "",
		OracleUser:      "",
		OracleTenancy:   "",
		OraclePublicKey: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3Fk7Tp4NwV8XmQ6LdJ9R
hY2BqG8Vz0kL5HgM7Xa4FrC9NsU1YvQ3KnR8WxL6ZqE2DfH5JtX3YmVgB8KsNp4Q
rL9XvT2HdQ8YwK5JmF3NxR7Pq4VsL8TgW6ZnM1KfY9DpX2RvQ8JwB3GtL5YxH4Nm
sK7VpX3LdR9FwT8MqN2HxY5BgJ6TsL4RpW8NvK3YxH5QmD9LwT2JsN8KgR4XpM7V
fY3BwL8TmN5KxQ2JgH7RsP9VwM4LnT8KpY3XgN5BwJ2HsR8TmL4VxQ9JpN3KgY7B
wR5TnM8LpJ2XgH4VsN9BwK3TmQ5RxL8JpY7NwH2VsR4KgM9TnL5BxJ3QwN8VpH7Y
KwIDAQAB
-----END PUBLIC KEY-----`,
		Operation: "",
	},
	{
		Id:                   utils.ObjectIdHex("689733b2a7a35eae0dbaea0d"),
		Datacenter:           utils.ObjectIdHex("689733b7a7a35eae0dbaea1b"),
		Zone:                 utils.ObjectIdHex("689733b7a7a35eae0dbaea1e"),
		Name:                 "pritunl-east3",
		Comment:              "",
		Types:                []string{"admin", "hypervisor"},
		Timestamp:            time.Now(),
		Port:                 443,
		NoRedirectServer:     false,
		Protocol:             "https",
		Hypervisor:           "kvm",
		Vga:                  "virtio",
		VgaRender:            "",
		AvailableRenders:     []string{},
		Gui:                  false,
		GuiUser:              "",
		GuiMode:              "",
		Certificates:         []primitive.ObjectID{},
		AdminDomain:          "",
		UserDomain:           "",
		WebauthnDomain:       "",
		RequestsMin:          56,
		ForwardedForHeader:   "",
		ForwardedProtoHeader: "",
		ExternalInterfaces:   []string{},
		ExternalInterfaces6:  []string{},
		InternalInterfaces:   []string{"bond0.2"},
		AvailableInterfaces: []ip.Interface{
			{Name: "bond0", Address: ""},
			{Name: "bond0.2", Address: "10.8.0.13"},
			{Name: "bond0.4", Address: "10.253.67.93"},
			{Name: "bonding_masters", Address: ""},
			{Name: "enp1s0f0", Address: ""},
			{Name: "enp1s0f1", Address: ""},
			{Name: "veth0", Address: ""},
		},
		AvailableBridges: []ip.Interface{
			{Name: "pritunlhost0", Address: "198.18.84.1"},
			{Name: "pritunlport0", Address: "198.19.96.1"},
		},
		AvailableVpcs:    []*cloud.Vpc{},
		CloudSubnets:     []string{},
		DefaultInterface: "bond0.4",
		NetworkMode:      "static",
		NetworkMode6:     "static",
		Blocks: []*node.BlockAttachment{
			{
				Interface: "bond0.4",
				Block:     utils.ObjectIdHex("689733b7a7a35eae0dbaea2f"),
			},
		},
		Blocks6: []*node.BlockAttachment{
			{
				Interface: "bond0.4",
				Block:     utils.ObjectIdHex("68973a47b5844593cf99cc7a"),
			},
		},
		Pools:  []primitive.ObjectID{},
		Shares: []*node.Share{},
		AvailableDrives: []*drive.Device{
			{Id: "nvme-INTEL_27Z1P0FGN"},
			{Id: "nvme-INTEL_27Z1P0FGN-part1"},
			{Id: "nvme-INTEL_27Z1P0FGN-part2"},
			{Id: "nvme-INTEL_27Z1P0FGN-part3"},
			{Id: "nvme-INTEL_42K1P0FGN"},
			{Id: "nvme-INTEL_42K1P0FGN-part1"},
			{Id: "nvme-INTEL_42K1P0FGN-part2"},
			{Id: "nvme-INTEL_42K1P0FGN-part3"},
		},
		InstanceDrives:          []*drive.Device{},
		NoHostNetwork:           false,
		NoNodePortNetwork:       false,
		HostNat:                 true,
		DefaultNoPublicAddress:  true,
		DefaultNoPublicAddress6: false,
		JumboFrames:             true,
		JumboFramesInternal:     true,
		Iscsi:                   false,
		LocalIsos:               nil,
		UsbPassthrough:          false,
		UsbDevices:              []*usb.Device{},
		PciPassthrough:          false,
		PciDevices:              []*pci.Device{},
		Hugepages:               false,
		HugepagesSize:           0,
		Firewall:                false,
		Roles:                   []string{"shape-m2"},
		Memory:                  41.02,
		HugePagesUsed:           0,
		Load1:                   24.63,
		Load5:                   23.32,
		Load15:                  21.43,
		CpuUnits:                128,
		MemoryUnits:             512,
		CpuUnitsRes:             64,
		MemoryUnitsRes:          298,
		PublicIps:               []string{"10.253.67.93"},
		PublicIps6: []string{
			"2001:db8:85a3:4d2f:9a47:3b6e:c829:4f16",
		},
		PrivateIps: map[string]string{
			"bond0.2": "10.8.0.13",
		},
		SoftwareVersion: constants.Version,
		Hostname:        "pritunl-east0",
		VirtPath:        "/var/lib/pritunl-cloud",
		CachePath:       "/var/cache/pritunl-cloud",
		TempPath:        "",
		OracleUser:      "",
		OracleTenancy:   "",
		OraclePublicKey: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu7nP2Kx4YmRa5TgL9Hs3
dW8JnF6QzV1MpC4BwX7Ka3Gt5RvN8YmL2Hs9Dx4TnQ6JpF8LwK3Vz5YmRs7NdT9H
gX2BpL4KwR8TmQ5NvJ3YxF7DsH9LwK2VmT8RgJ4NpX5BwL3HsY7TmQ9KxF2DpN8V
wJ3LsT4HgR9YmK5NxB2FwL7TsH8KpQ3XmJ4DgN9BwY2RsL5HxK7VmT3NpF8YwJ4D
gR2TsL9KxH5BmN3VwQ8JpY7LsT4HgK2NxR9FmL3BwJ5TsN8YpK4VxH7DgQ2LmR9N
wJ3BsT5HxL8KpN2YmF4DgR7VwQ3TsJ9KxH5BmL8NpY2FgT4RwK7VsH9JmQ3LxN8D
FwIDAQAB
-----END PUBLIC KEY-----`,
		Operation: "",
	},
	{
		Id:                   utils.ObjectIdHex("689733b2a7a35eae0dbaea0e"),
		Datacenter:           utils.ObjectIdHex("689733b7a7a35eae0dbaea1b"),
		Zone:                 utils.ObjectIdHex("689733b7a7a35eae0dbaea1e"),
		Name:                 "pritunl-east4",
		Comment:              "",
		Types:                []string{"admin", "hypervisor"},
		Timestamp:            time.Now(),
		Port:                 443,
		NoRedirectServer:     false,
		Protocol:             "https",
		Hypervisor:           "kvm",
		Vga:                  "virtio",
		VgaRender:            "",
		AvailableRenders:     []string{},
		Gui:                  false,
		GuiUser:              "",
		GuiMode:              "",
		Certificates:         []primitive.ObjectID{},
		AdminDomain:          "",
		UserDomain:           "",
		WebauthnDomain:       "",
		RequestsMin:          76,
		ForwardedForHeader:   "",
		ForwardedProtoHeader: "",
		ExternalInterfaces:   []string{},
		ExternalInterfaces6:  []string{},
		InternalInterfaces:   []string{"bond0.2"},
		AvailableInterfaces: []ip.Interface{
			{Name: "bond0", Address: ""},
			{Name: "bond0.2", Address: "10.8.0.14"},
			{Name: "bond0.4", Address: "10.253.67.94"},
			{Name: "bonding_masters", Address: ""},
			{Name: "enp1s0f0", Address: ""},
			{Name: "enp1s0f1", Address: ""},
			{Name: "veth0", Address: ""},
		},
		AvailableBridges: []ip.Interface{
			{Name: "pritunlhost0", Address: "198.18.84.1"},
			{Name: "pritunlport0", Address: "198.19.96.1"},
		},
		AvailableVpcs:    []*cloud.Vpc{},
		CloudSubnets:     []string{},
		DefaultInterface: "bond0.4",
		NetworkMode:      "static",
		NetworkMode6:     "static",
		Blocks: []*node.BlockAttachment{
			{
				Interface: "bond0.4",
				Block:     utils.ObjectIdHex("689733b7a7a35eae0dbaea2f"),
			},
		},
		Blocks6: []*node.BlockAttachment{
			{
				Interface: "bond0.4",
				Block:     utils.ObjectIdHex("68973a47b5844593cf99cc7a"),
			},
		},
		Pools:  []primitive.ObjectID{},
		Shares: []*node.Share{},
		AvailableDrives: []*drive.Device{
			{Id: "nvme-INTEL_27Z1P0FGN"},
			{Id: "nvme-INTEL_27Z1P0FGN-part1"},
			{Id: "nvme-INTEL_27Z1P0FGN-part2"},
			{Id: "nvme-INTEL_27Z1P0FGN-part3"},
			{Id: "nvme-INTEL_42K1P0FGN"},
			{Id: "nvme-INTEL_42K1P0FGN-part1"},
			{Id: "nvme-INTEL_42K1P0FGN-part2"},
			{Id: "nvme-INTEL_42K1P0FGN-part3"},
		},
		InstanceDrives:          []*drive.Device{},
		NoHostNetwork:           false,
		NoNodePortNetwork:       false,
		HostNat:                 true,
		DefaultNoPublicAddress:  true,
		DefaultNoPublicAddress6: false,
		JumboFrames:             true,
		JumboFramesInternal:     true,
		Iscsi:                   false,
		LocalIsos:               nil,
		UsbPassthrough:          false,
		UsbDevices:              []*usb.Device{},
		PciPassthrough:          false,
		PciDevices:              []*pci.Device{},
		Hugepages:               false,
		HugepagesSize:           0,
		Firewall:                false,
		Roles:                   []string{"shape-m2"},
		Memory:                  41.02,
		HugePagesUsed:           0,
		Load1:                   88.45,
		Load5:                   83.13,
		Load15:                  72.34,
		CpuUnits:                128,
		MemoryUnits:             512,
		CpuUnitsRes:             45,
		MemoryUnitsRes:          242,
		PublicIps:               []string{"10.253.67.94"},
		PublicIps6: []string{
			"2001:db8:85a3:4d2f:6f15:d8c3:2a94:e7b1",
		},
		PrivateIps: map[string]string{
			"bond0.2": "10.8.0.14",
		},
		SoftwareVersion: constants.Version,
		Hostname:        "pritunl-east0",
		VirtPath:        "/var/lib/pritunl-cloud",
		CachePath:       "/var/cache/pritunl-cloud",
		TempPath:        "",
		OracleUser:      "",
		OracleTenancy:   "",
		OraclePublicKey: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx9SLk4Pm3VaRtN8Yw2Hf
jK5TgQ7BnM2XpL4DwV8Ha6FsR9YmJ3KxC5NtQ8LwP7DgH2VmF4TsK9XpN3BwJ8Rg
mL5YxH7TsQ2NpK4VwF8DgJ3BmR9LxT5KsN2HwY7FpQ8VmJ4TgL3NxK9BwH5DsR2Y
mF7KpT8LwQ3VgN4JxH9BsK2TmL5DwR8YpF3NxQ7KgJ4VsH9BmT2LwK8DxN5YpF3R
gJ7TsL4KwH9VmQ2NxB8FpY3DgK5TsR9LwJ2HmN4BxF7VpQ8KgL3TsY9NwH5DmK4J
xR2BgF8TpL7VsN3KwQ9YmH4DgJ5BxT2LsK8FpN3VwR7YgH4TmQ9KsL2BxJ5NpF8D
RwIDAQAB
-----END PUBLIC KEY-----`,
		Operation: "",
	},
	{
		Id:                   utils.ObjectIdHex("689733b2a7a35eae0dbaea0f"),
		Datacenter:           utils.ObjectIdHex("689733b7a7a35eae0dbaea1b"),
		Zone:                 utils.ObjectIdHex("689733b7a7a35eae0dbaea1e"),
		Name:                 "pritunl-east5",
		Comment:              "",
		Types:                []string{"admin", "hypervisor"},
		Timestamp:            time.Now(),
		Port:                 443,
		NoRedirectServer:     false,
		Protocol:             "https",
		Hypervisor:           "kvm",
		Vga:                  "virtio",
		VgaRender:            "",
		AvailableRenders:     []string{},
		Gui:                  false,
		GuiUser:              "",
		GuiMode:              "",
		Certificates:         []primitive.ObjectID{},
		AdminDomain:          "",
		UserDomain:           "",
		WebauthnDomain:       "",
		RequestsMin:          12,
		ForwardedForHeader:   "",
		ForwardedProtoHeader: "",
		ExternalInterfaces:   []string{},
		ExternalInterfaces6:  []string{},
		InternalInterfaces:   []string{"bond0.2"},
		AvailableInterfaces: []ip.Interface{
			{Name: "bond0", Address: ""},
			{Name: "bond0.2", Address: "10.8.0.15"},
			{Name: "bond0.4", Address: "10.253.67.95"},
			{Name: "bonding_masters", Address: ""},
			{Name: "enp1s0f0", Address: ""},
			{Name: "enp1s0f1", Address: ""},
			{Name: "veth0", Address: ""},
		},
		AvailableBridges: []ip.Interface{
			{Name: "pritunlhost0", Address: "198.18.84.1"},
			{Name: "pritunlport0", Address: "198.19.96.1"},
		},
		AvailableVpcs:    []*cloud.Vpc{},
		CloudSubnets:     []string{},
		DefaultInterface: "bond0.4",
		NetworkMode:      "static",
		NetworkMode6:     "static",
		Blocks: []*node.BlockAttachment{
			{
				Interface: "bond0.4",
				Block:     utils.ObjectIdHex("689733b7a7a35eae0dbaea2f"),
			},
		},
		Blocks6: []*node.BlockAttachment{
			{
				Interface: "bond0.4",
				Block:     utils.ObjectIdHex("68973a47b5844593cf99cc7a"),
			},
		},
		Pools:  []primitive.ObjectID{},
		Shares: []*node.Share{},
		AvailableDrives: []*drive.Device{
			{Id: "nvme-INTEL_27Z1P0FGN"},
			{Id: "nvme-INTEL_27Z1P0FGN-part1"},
			{Id: "nvme-INTEL_27Z1P0FGN-part2"},
			{Id: "nvme-INTEL_27Z1P0FGN-part3"},
			{Id: "nvme-INTEL_42K1P0FGN"},
			{Id: "nvme-INTEL_42K1P0FGN-part1"},
			{Id: "nvme-INTEL_42K1P0FGN-part2"},
			{Id: "nvme-INTEL_42K1P0FGN-part3"},
		},
		InstanceDrives:          []*drive.Device{},
		NoHostNetwork:           false,
		NoNodePortNetwork:       false,
		HostNat:                 true,
		DefaultNoPublicAddress:  true,
		DefaultNoPublicAddress6: false,
		JumboFrames:             true,
		JumboFramesInternal:     true,
		Iscsi:                   false,
		LocalIsos:               nil,
		UsbPassthrough:          false,
		UsbDevices:              []*usb.Device{},
		PciPassthrough:          false,
		PciDevices:              []*pci.Device{},
		Hugepages:               false,
		HugepagesSize:           0,
		Firewall:                false,
		Roles:                   []string{"shape-m2"},
		Memory:                  41.02,
		HugePagesUsed:           0,
		Load1:                   53.44,
		Load5:                   43.75,
		Load15:                  43.93,
		CpuUnits:                128,
		MemoryUnits:             512,
		CpuUnitsRes:             76,
		MemoryUnitsRes:          346,
		PublicIps:               []string{"10.253.67.95"},
		PublicIps6: []string{
			"2001:db8:85a3:4d2f:8d2c:1fa7:b653:9e48",
		},
		PrivateIps: map[string]string{
			"bond0.2": "10.8.0.15",
		},
		SoftwareVersion: constants.Version,
		Hostname:        "pritunl-east0",
		VirtPath:        "/var/lib/pritunl-cloud",
		CachePath:       "/var/cache/pritunl-cloud",
		TempPath:        "",
		OracleUser:      "",
		OracleTenancy:   "",
		OraclePublicKey: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1pK7Gm4XwQ9RsT2NvH8Bf
jL5DgY3KpM2TwV8NxH4FsQ9BmL7YgK3VpT8DwR5NxJ2HmF4KgQ7TsL9BwY3VpN8R
xK5DmH2FgT9LwJ4NsQ7BpV3KxY8TmL5HgR2DwN9FpK4VsT3BxJ7YmQ8LgH2NwK5D
pF9TxR3VsL4KgY7BmN2HwJ8FpQ5TxK9DsL3VgH4NmR7BwY2KpT8FxJ9LsQ3DgN5V
mH7BwK4TpL2RxF9NsY3KgQ8DmJ5VwH7BpT2LxK4FgN9RsQ3TmL8YwJ5DpH7KxF2N
gV4BsT9LmQ3KwR8YpN5DxH7FgJ2TsL4BwK9VmQ3NpY8RxT5LgH2DsK7BmF4JwN9Q
TwIDAQAB
-----END PUBLIC KEY-----`,
		Operation: "",
	},
}
